import {
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BgColorsOutlined,
  BookOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  CalendarOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloudServerOutlined,
  CodeOutlined,
  CompressOutlined,
  ControlOutlined,
  CopyOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DownloadOutlined,
  DragOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileExcelOutlined,
  FilePdfOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileZipOutlined,
  FormOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  GithubOutlined,
  GlobalOutlined,
  IdcardOutlined,
  KeyOutlined,
  LeftOutlined,
  LinkOutlined,
  LockOutlined,
  LoginOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  NumberOutlined,
  PartitionOutlined,
  PhoneOutlined,
  ProfileOutlined,
  QqOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  RightOutlined,
  SearchOutlined,
  SelectOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  SkinOutlined,
  SlidersOutlined,
  StarOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  TranslationOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserOutlined,
  WechatOutlined,
} from '@ant-design/icons';
import React, { type ReactNode } from 'react';

export const ruoyiMenuIconNames = [
  '404',
  'bug',
  'build',
  'button',
  'caret-back',
  'caret-forward',
  'cascader',
  'category',
  'chart',
  'checkbox',
  'clipboard',
  'code',
  'color',
  'company',
  'component',
  'dashboard',
  'date',
  'date-range',
  'dict',
  'documentation',
  'download',
  'drag',
  'druid',
  'edit',
  'education',
  'email',
  'example',
  'excel',
  'exit-fullscreen',
  'eye',
  'eye-open',
  'finish',
  'form',
  'fullscreen',
  'gitee',
  'github',
  'guide',
  'icon',
  'input',
  'international',
  'job',
  'language',
  'link',
  'list',
  'lock',
  'log',
  'logininfor',
  'maxkey',
  'message',
  'model',
  'money',
  'monitor',
  'my-copy',
  'my-task',
  'nested',
  'number',
  'online',
  'password',
  'pdf',
  'people',
  'peoples',
  'phone',
  'post',
  'process-definition',
  'qq',
  'question',
  'radio',
  'rate',
  'redis',
  'redis-list',
  'row',
  'search',
  'select',
  'server',
  'shopping',
  'size',
  'skill',
  'slider',
  'star',
  'swagger',
  'switch',
  'system',
  'tab',
  'table',
  'textarea',
  'theme',
  'time',
  'time-range',
  'tool',
  'topiam',
  'tree',
  'tree-table',
  'upload',
  'user',
  'validCode',
  'waiting',
  'wechat',
  'workflow',
  'zip',
] as const;

const iconMap: Record<string, ReactNode> = {
  '404': <FileUnknownOutlined />,
  bug: <BugOutlined />,
  build: <BuildOutlined />,
  button: <ControlOutlined />,
  'caret-back': <LeftOutlined />,
  'caret-forward': <RightOutlined />,
  cascader: <BranchesOutlined />,
  category: <TagsOutlined />,
  chart: <BarChartOutlined />,
  checkbox: <CheckSquareOutlined />,
  clipboard: <ProfileOutlined />,
  code: <CodeOutlined />,
  color: <BgColorsOutlined />,
  company: <BankOutlined />,
  component: <AppstoreOutlined />,
  dashboard: <DashboardOutlined />,
  date: <CalendarOutlined />,
  'date-range': <CalendarOutlined />,
  dict: <BookOutlined />,
  documentation: <FileTextOutlined />,
  download: <DownloadOutlined />,
  drag: <DragOutlined />,
  druid: <DatabaseOutlined />,
  edit: <EditOutlined />,
  education: <ReadOutlined />,
  email: <MailOutlined />,
  example: <FormOutlined />,
  excel: <FileExcelOutlined />,
  'exit-fullscreen': <FullscreenExitOutlined />,
  eye: <EyeInvisibleOutlined />,
  'eye-open': <EyeOutlined />,
  finish: <CheckCircleOutlined />,
  form: <FormOutlined />,
  fullscreen: <FullscreenOutlined />,
  gitee: <GithubOutlined />,
  github: <GithubOutlined />,
  guide: <QuestionCircleOutlined />,
  icon: <AppstoreOutlined />,
  input: <FormOutlined />,
  international: <GlobalOutlined />,
  job: <ToolOutlined />,
  language: <TranslationOutlined />,
  link: <LinkOutlined />,
  list: <UnorderedListOutlined />,
  lock: <LockOutlined />,
  log: <FileTextOutlined />,
  logininfor: <LoginOutlined />,
  maxkey: <KeyOutlined />,
  message: <MessageOutlined />,
  model: <DeploymentUnitOutlined />,
  money: <MoneyCollectOutlined />,
  monitor: <MonitorOutlined />,
  'my-copy': <CopyOutlined />,
  'my-task': <AuditOutlined />,
  nested: <NodeIndexOutlined />,
  number: <NumberOutlined />,
  online: <CloudServerOutlined />,
  password: <KeyOutlined />,
  pdf: <FilePdfOutlined />,
  people: <TeamOutlined />,
  peoples: <TeamOutlined />,
  phone: <PhoneOutlined />,
  post: <IdcardOutlined />,
  'process-definition': <PartitionOutlined />,
  qq: <QqOutlined />,
  question: <QuestionCircleOutlined />,
  radio: <CheckCircleOutlined />,
  rate: <StarOutlined />,
  redis: <DatabaseOutlined />,
  'redis-list': <DatabaseOutlined />,
  row: <UnorderedListOutlined />,
  search: <SearchOutlined />,
  select: <SelectOutlined />,
  server: <CloudServerOutlined />,
  shopping: <ShoppingCartOutlined />,
  size: <CompressOutlined />,
  skill: <ToolOutlined />,
  slider: <SlidersOutlined />,
  star: <StarOutlined />,
  swagger: <ApiOutlined />,
  switch: <SwapOutlined />,
  system: <SettingOutlined />,
  tab: <TableOutlined />,
  table: <TableOutlined />,
  textarea: <FileTextOutlined />,
  theme: <SkinOutlined />,
  time: <ClockCircleOutlined />,
  'time-range': <ClockCircleOutlined />,
  tool: <ToolOutlined />,
  topiam: <MobileOutlined />,
  tree: <ApartmentOutlined />,
  'tree-table': <PartitionOutlined />,
  upload: <UploadOutlined />,
  user: <UserOutlined />,
  validcode: <ExclamationCircleOutlined />,
  waiting: <ClockCircleOutlined />,
  wechat: <WechatOutlined />,
  workflow: <PartitionOutlined />,
  zip: <FileZipOutlined />,
};

export const normalizeRuoyiIconKey = (icon?: string) =>
  (icon || '').trim().replace(/^#/, '').toLowerCase();

export const getRuoyiIconNode = (icon?: string) => {
  const key = normalizeRuoyiIconKey(icon);
  if (!key) return undefined;
  return iconMap[key] || <AppstoreOutlined />;
};

export const toRuoyiMenuIcon = (icon?: string) => getRuoyiIconNode(icon);
